[functions.prioritize-tasks]
verify_jwt = false

[functions.analyze-attendees]
verify_jwt = false

[functions.research-company]
verify_jwt = false

[functions.generate-sales-intelligence]
verify_jwt = false
